spring.application.name=evento
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_8OQKTvL1HcjU@ep-falling-glitter-accrlo5p-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=postgres
spring.datasource.password=npg_8OQKTvL1HcjU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080